#
# _config.yml for social-post
#

exclude: [ "CNAME", "Gemfile*", "LICENSE.txt", "README.md", "tmp", "*.sh" ]
include: [".well-known"]
production_url: https://social-post.marcuse.info
title : Social Post CLI
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..3
  # https://github.com/gettalong/kramdown/issues/155
  # not working: parse_block_html: true
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
